config/routes.rb
Rails.application.routes.draw do
  resources :payments, only: [:index] do
    member do
      put 'approve', to: 'payment_approval#perform'
      put 'reject', to: 'payment_rejection#perform'
    end
  end

  root "payments#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true
  validates :payment_id, presence: true
  validates :name, uniqueness: { scope: :payment_id }
end

app/models/payment.rb
class Payment < ApplicationRecord
  validates :invoice_reference_id, presence: true
  validates :description, presence: true
  validates :amount_currency, presence: true

  monetize :amount_cents, allow_nil: false

  validates :invoice_reference_id, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/payment_approval_controller.rb
class PaymentApprovalController < ApplicationController
  def perform
    result = ApprovePayment.new(payment).perform!

    flash[:notice] = result[:message]
    redirect_to payments_path
  end

  private

  def payment
    Payment.find(params[:id])
  end
end

app/controllers/payment_rejection_controller.rb
class PaymentRejectionController < ApplicationController
  def perform
    result = RejectPayment.new(payment).perform!

    flash[:notice] = result[:message]
    redirect_to payments_path
  end

  private

  def payment
    Payment.find(params[:id])
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
    @payments = Payment.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
  def status(payment)
    if payment.approved_at
      'approved'
    elsif payment.rejected_at
      'rejected'
    else
      'pending for approval'
    end
  end

  def can_approve?(payment)
    !payment.approved_at && !payment.rejected_at
  end

  def can_reject?(payment)
    !payment.approved_at && !payment.rejected_at
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManagerApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash.any? %>
      <% flash.each do |type, msg| %>
        <div>
          <%= msg %>
        </div>
      <% end %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/payments/index.html.erb
<% if @payments.present? %>
  <table>
  <tr>
    <th>Invoice reference id</th>
    <th> Amount</th>
    <th> Amount currency</th>
    <th> Status</th>
    <th> Description</th>
    <th> Created at</th>
    <th> Approved at</th>
    <th> Rejected at</th>
    <th> Approve </th>
    <th> Reject </th>
  </tr>

  <% @payments.each do |payment| %>
    <tr>
      <td> <%= payment.invoice_reference_id %> </td>
      <td><%= payment.amount %></td>
      <td> <%= payment.amount_currency %> </td>
      <td> <%= status(payment) %> </td>
      <td> <%= payment.description %> </td>
      <td> <%= payment.created_at %> </td>
      <td> <%= payment.approved_at %> </td>
      <td> <%= payment.rejected_at %> </td>
      <% if can_approve?(payment) %>
        <td> <%= link_to 'Approve', approve_payment_path(payment), data: { "turbo-method": :put } %> </td>
      <% end %>
      <% if can_reject?(payment) %>
        <td> <%= link_to 'Reject', reject_payment_path(payment), data: { "turbo-method": :put } %> </td>
      <% end %>
    </tr>
  <% end %>
</table>
<% else %>
  <p> No payments found </p>
<% end %>